version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: fitness-postgres
    environment:
      POSTGRES_USER: jndambiri
      POSTGRES_PASSWORD: "!56v-8c)&ag_kx"
      POSTGRES_DB: fitnessdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jndambiri -d fitnessdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fitness-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    container_name: fitness-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fitnessdb
      SPRING_DATASOURCE_USERNAME: jndambiri
      SPRING_DATASOURCE_PASSWORD: "!56v-8c)&ag_kx"

  frontend:
    build: ./frontend
    container_name: fitness-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend



volumes:
  postgres_data:
  redis_data:
