sonar.projectKey=joanwanjiku_thryve-ai
sonar.organization=joanwanjiku
sonar.host.url=https://sonarcloud.io

# Source and test directories
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.source=17

# JaCoCo coverage report location
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclude generated / boilerplate code from analysis
sonar.exclusions=**/dto/**,**/entity/**,**/configs/**,**/mapper/**

# Encoding
sonar.sourceEncoding=UTF-8